# .github/workflows/main.yml
name: Debian BPI-R3 Build

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Zusätzliche Pakete (optional, mit Leerzeichen getrennt)'
        type: string
        required: false

jobs:
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Aktualisiert auf v4, da v2 veraltet ist

      - name: Setup env
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: "*_arm*.tar.gz"
          key: ${{ runner.os }}-chroot
          restore-keys: ${{ runner.os }}-chroot

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 parted qemu-user-static debootstrap binfmt-support mtd-utils

      - name: Build R3 Debian Trixie Image (SDMMC)
        run: |
          # Falls optionale Zusatzpakete über GitHub Actions angegeben wurden:
          if [ -n "${{ inputs.packages }}" ]; then
            echo -e "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r3.conf
          fi
          
          # Führt den Build exklusiv für bpi-r3, trixie und Kernel 6.18 aus
          # Das Skript erzeugt hierbei standardmäßig das sdmmc-Image
          ./buildimg.sh bpi-r3 trixie 6.18

      - name: Upload Image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi-r3-debian-trixie-sdmmc-${{ env.DT }}
          path: "*.img.gz*"
          if-no-files-found: error