name: Debian BPI-R3 Build

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'ppp pppoe pppoeconf ifupdown systemd-networking systemd-networkd nftables iproute2 iptables tcpdump ethtool ethtool-dev conntrack conntrack-tools dnsmasq bind9 bind9-utils unbound resolvconf wireguard-tools openssh-server dropbear fail2ban chrony systemd-timesyncd curl wget ca-certificates gnupg lsb-release sudo bash-completion vim-nox nano htop btop iotop iftop nload bmon vnstat net-tools traceroute mtr-tiny ping inetutils-traceroute iputils-ping arp-scan nmap rsync less logrotate rsyslog journalctl collectd prometheus-node-exporter smartmontools lm-sensors lm-sensors-applet usbutils pciutils lsscsi hdparm mc tmux screen git awk sed grep coreutils findutils util-linux procps psmisc bridge-utils vlan ethtool libnftables1 ipset ipcalc qrencode zstd gzip bzip2 xz-utils unzip tar make gcc g++ pkg-config python3 python3-venv python3-pip bash-completion apparmor apparmor-utils unattended-upgrades needrestart augeas-tools dhcpcd5 isc-dhcp-client irqbalance cpufrequtils thermald rclone vi vim dnsmasq hostapd syslog-ng busybox-syslog curl wget ca-certificates tail lm-sensors'
        type: string
        required: false

jobs:
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          permissions:
            contents: write  # <- HINZUFÜGEN für Skript-Permissions [web:24]

      - name: Setup env
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: "*_arm*.tar.gz"
          key: ${{ runner.os }}-chroot
          restore-keys: ${{ runner.os }}-chroot

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 parted qemu-user-static debootstrap binfmt-support mtd-utils

      - name: Make buildimg.sh executable
        run: |
          chmod +x buildimg.sh  # <- WICHTIG! [web:24][web:27]
          ls -la buildimg.sh    # Debug: Permissions prüfen

      - name: Build R3 Debian Trixie Image (SDMMC)
        run: |
          if [ -n "${{ inputs.packages }}" ]; then
            echo -e "userpackages="${{ inputs.packages }}"" >> sourcefiles_bpi-r3.conf
          fi
          ./buildimg.sh bpi-r3 trixie 6.18

      - name: Upload Image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi-r3-debian-trixie-sdmmc-${{ env.DT }}
          path: "*.img.gz*"
          if-no-files-found: error